version: 0.2
env:
   SPECTRAL_DSN: https://spu-66dcdd6c088d4a89bdb47454c4ff3672@spectral-us.checkpoint.com
phases: 
    build: 
        commands: 
            - npm i --save 
    post_build:
        commands:
           - curl -L "https://spectral-eu.checkpoint.com/latest/x/sh?dsn=$SPECTRAL_DSN"| sh
           - SPECTRAL_DSN=https://spu-66dcdd6c088d4a89bdb47454c4ff3672@spectral-us.checkpoint.com $HOME/.spectral/spectral scan --ok  --include-tags base,audit
artifacts: 
    files: 
        - '**/*'